server:
  port : 8100

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
#    url: jdbc:log4jdbc:h2:tcp://localhost/~/test
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  config-location: classpath:sql-mapper-config.xml
  mapper-locations: classpath:sqlmap/**/*_SQL.xml

logging:
  level:
    root: INFO
    jdbc: OFF
    jdbc.connection: OFF
    jdbc.sqlonly: OFF
    jdbc.sqltiming: DEBUG
    jdbc.audit : OFF
    jdbc.resultset : OFF
    jdbc.resultsettable: OFF
    org.springframework.web: DEBUG
    com.zaxxer.hikari.HikariDataSource: ERROR